### ISSUE TITLE
Cookies problem

### ISSUE THREAD

**Issue by jlcanovas** [jlcanovas/flyzer#7]
It seems that there is some kind of problem with the cookies:

> A cookie associated with a cross-site resource at http://d3js.org/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by StuartMellor** [comment]
I'm also getting this warning. Would be great to resolve this so that I can debug without having this plastered over the console.......

**Comment by jlcanovas** [comment]
Thanks @StuartMellor , you are right, it's really a pain in the ass :)

I'll try to have a look at this next week!

**Comment by StuartMellor** [comment]
Thanks @jlcanovas !! 😃

**Comment by jlcanovas** [comment]
Commit 86be5453d55e2f9fc43e969f473682c25544c687 fixes this by using D3 locally.
